#!/bin/sh
echo "Type (C-a x) to terminate qemu in -nographic mode"
echo
qemu-system-arm \
    -s \
    -M versatilepb \
    -m 128M \
    -nographic \
    \
    -net user \
    -net nic,model=rtl8139 \
    \
    -usb \
    \
    -kernel versatilepb.img \
    \
    "$@"
