#!/bin/sh

cat <<EOF > experiment.s
	.text
	.global e
e:
EOF
echo "$1" >> experiment.s
cat experiment.s
arm-none-eabi-as -mfpu=vfpv3 -o experiment.o experiment.s
arm-none-eabi-objdump -d experiment.o
