#!/bin/sh
echo
echo "Graphical output via VNC at :0"
echo

IOOPTIONS="-serial stdio -vnc :0"
# IOOPTIONS="-nographic"

(sleep 1; vncviewer localhost:0 >/dev/null 2>&1) &
qemu-system-arm \
    -M versatilepb \
    -m 128M \
    $IOOPTIONS \
    \
    -net user \
    -net nic,model=rtl8139 \
    \
    -usb \
    \
    -kernel versatilepb-graphics.img \
    \
    "$@"
